version: '3.8'

services:

  postgres:
    image: postgres
    container_name: connection-postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: connection

volumes:
  postgres:
